const express=require('express'),mongoose=require('mongoose'),cors=require('cors'),bcrypt=require('bcryptjs'),jwt=require('jsonwebtoken'),dotenv=require('dotenv'),path=require('path'),User=require('./models/User');
dotenv.config();
const app=express();
app.use(cors({origin:'*',credentials:true}));app.use(express.json());app.use(express.static(path.join(__dirname,'../frontend')));
mongoose.connect(process.env.MONGO_URI||'mongodb://127.0.0.1:27017/maapah').then(()=>console.log('MongoDB connected')).catch(e=>console.error(e));
const SECRET=process.env.JWT_SECRET||'maapah-dev-secret';
function auth(req,res,next){const t=(req.headers.authorization||'').split(' ')[1];if(!t)return res.status(401).json({error:'No token'});try{req.user=jwt.verify(t,SECRET);next();}catch{res.status(401).json({error:'Invalid token'});}}
app.post('/api/auth/register',async(req,res)=>{try{const{username,password}=req.body;if(!username||!password)return res.status(400).json({error:'Fields required'});if(username.length<3)return res.status(400).json({error:'Username min 3 chars'});if(password.length<6)return res.status(400).json({error:'Password min 6 chars'});if(await User.findOne({username:username.toLowerCase()}))return res.status(409).json({error:'Username taken'});const hash=await bcrypt.hash(password,12);const user=await User.create({username:username.toLowerCase(),password:hash});const token=jwt.sign({id:user._id,username:user.username},SECRET,{expiresIn:'7d'});res.status(201).json({token,user:{id:user._id,username:user.username,level:user.level,xp:user.xp,score:user.score}});}catch(e){res.status(500).json({error:e.message});}});
app.post('/api/auth/login',async(req,res)=>{try{const{username,password}=req.body;if(!username||!password)return res.status(400).json({error:'Fields required'});const user=await User.findOne({username:username.toLowerCase()});if(!user||!await bcrypt.compare(password,user.password))return res.status(401).json({error:'Invalid credentials'});const token=jwt.sign({id:user._id,username:user.username},SECRET,{expiresIn:'7d'});res.json({token,user:{id:user._id,username:user.username,level:user.level,xp:user.xp,score:user.score}});}catch(e){res.status(500).json({error:e.message});}});
app.get('/api/auth/me',auth,async(req,res)=>{try{const user=await User.findById(req.user.id).select('-password');res.json({user});}catch(e){res.status(500).json({error:e.message});}});
app.patch('/api/user/progress',auth,async(req,res)=>{try{const{xp,level,score,monstersDefeated}=req.body;const u={};if(xp!==undefined)u.xp=xp;if(level!==undefined)u.level=level;if(score!==undefined)u.score=score;if(monstersDefeated!==undefined)u.monstersDefeated=monstersDefeated;const user=await User.findByIdAndUpdate(req.user.id,{$set:u},{new:true}).select('-password');res.json({user});}catch(e){res.status(500).json({error:e.message});}});
app.get('/api/leaderboard',async(req,res)=>{try{const users=await User.find({}).sort({score:-1}).limit(10).select('username level score monstersDefeated');res.json({leaderboard:users});}catch(e){res.status(500).json({error:e.message});}});
app.get('/api/music/search',auth,async(req,res)=>{try{const q=encodeURIComponent(req.query.q||'');if(!q)return res.status(400).json({error:'Query required'});const r=await fetch('https://musicbrainz.org/ws/2/recording/?query='+q+'&limit=5&fmt=json',{headers:{'User-Agent':'MaaPahDeed/1.0'}});const data=await r.json();res.json({results:(data.recordings||[]).map(rec=>({id:rec.id,title:rec.title,artist:(rec['artist-credit']&&rec['artist-credit'][0]&&rec['artist-credit'][0].name)||'Unknown',duration:rec.length?Math.round(rec.length/1000):null}))});}catch(e){res.status(500).json({error:'MusicBrainz failed'});}});
app.get('/api/music/key-suggest',auth,(req,res)=>{const notes=(req.query.notes||'').split(',').map(n=>n.trim()).filter(Boolean);const SCALES={'C major':['C','D','E','F','G','A','B'],'G major':['G','A','B','C','D','E','F#'],'D major':['D','E','F#','G','A','B','C#'],'A minor':['A','B','C','D','E','F','G'],'E minor':['E','F#','G','A','B','C','D'],'D minor':['D','E','F','G','A','Bb','C']};const s=Object.entries(SCALES).map(([key,scale])=>({key,score:notes.length?Math.round(notes.filter(n=>scale.includes(n)).length/notes.length*100):0})).sort((a,b)=>b.score-a.score).slice(0,3);res.json({suggestions:s});});
app.get('/api/health',(req,res)=>res.json({status:'ok'}));
app.get('*',(req,res)=>res.sendFile(path.join(__dirname,'../frontend/index.html')));
const PORT=process.env.PORT||5001;
app.listen(PORT,()=>console.log('MaaPahDeed running on http://localhost:'+PORT));
